### ISSUE TITLE
Not Found error {js}

### ISSUE THREAD

**Issue by Misagh90** [silverstripe-australia/silverstripe-advancedworkflow#275]
Hi,
I install advaced workflow and set config of this add-on like Guideline in silverstripe
but when i push button as a editor to admin to approve it , an error comes and don't send any Email to admin.

![not found](https://cloud.githubusercontent.com/assets/6697222/16544531/7bdf16e6-411f-11e6-8bac-3006c3aadb36.png)
Is there any more config?!

**Comment by nyeholt** [comment]
What version of SilverStripe, and what version of the module are you using? Note that the 'master' branch version of the module will only work on the pre-alpha version of SilverStripe - check the '3' branch for a SS3 compatible version.

**Comment by Misagh90** [comment]
i used master branch and SS3.4, i changed it to the 3.2 and change the php version to 5.6 and it's worked

**Comment by flamerohr** [comment]
I think this is related to entwine being updated and the namespacing had some regression issues, it was fixed in the master branch by changing the top line in `WorkflowField.js` to
```
jQuery.entwine("ss.workflow", function($) {
```

**Comment by tractorcow** [comment]
It seems using the right version of advworkflow with framework resolved the issue, so it's ok to close this?
