### ISSUE TITLE
Embargo and Expiry logic handling

### ISSUE THREAD

**Issue by flamerohr** [silverstripe-australia/silverstripe-advancedworkflow#282]
Hey guys,

We've been investigating the logic behind the handling for Embargo and Expiry and had found it confusing to understand some cases.
From our perspective, the following rules helped clarify what would be expected to happen when the conditions are met.
```
embargo before (<) expiry            |  create publish job & unpublish job
embargo after or equals (>=) expiry  |  Don't create any jobs (and add validation on request)
expiry in the past                   |  create unpublish job ONLY (remove publish job if applicable)
embargo in the past                  |  create publish job (and unpublish job if applicable)
```

Some use cases that we ran into were:
* Some tried embargoing and expiring at the exact same time, in future and past. The outcomes were inconsistent, for future it would create both jobs and so whichever job finishes last is what the effect is. And for past it would not create any jobs and leave the fields populated.
* Delayed approvals, both embargo and expiry has passed => expiry should run.
* Some tries to expiry first then embargo => invalid (?) and a warning should show for this

We were considering that expiry before embargo was quite a weird use case, and perhaps it'd be simpler to validate and prevent this from happening. What do you guys think?

**Comment by tractorcow** [comment]
I thought that embargo after expiry meant "unpublish, but then publish again at embargo"?

**Comment by flamerohr** [comment]
Yeah, that's what it means.
But we were thinking that because it's quite an edge case, it would be better to make the option for "expiry before embargo" invalid.

We're definitely addressing the inconsistency for when "embargo equals expiry", and thought it'd help to address "expiry before embargo" while we're at it.
